version: "3.9"

services:
  mysql:
    container_name: trilogy-test
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trilogy