default: &default
  adapter: mysql2
  pool: 5
  host: 127.0.0.1
  port: 3306
  timeout: 5000
  username: root
  password: password

development:
  <<: *default
  database: trilogy

test:
  <<: *default
  database: trilogy_test

production:
  <<: *default
  database: trilogy
